import { defaultPaymentMethods } from "./payments";
import type { Order, PaymentMethodConfig, Product, ShippingOption, ShippingService } from "./types";

export const products: Product[] = [
  {
    id: "prod-101",
    code: "101",
    name: "Cardigan Knit Elegance",
    description: "Rajut lembut dengan potongan rileks untuk tampilan feminin sehari-hari.",
    price: 199_000,
    image: "/products/cardigan-101.png",
    images: ["/products/cardigan-101.png"],
    colors: ["Burgundy", "Mocha", "Navy"],
    colorHex: { Burgundy: "#7d1837", Mocha: "#9b735b", Navy: "#20344e" },
    sizes: ["S", "M", "L", "XL"],
    stock: 12,
    reserved: 2,
    isLive: true,
    active: true,
    weightGrams: 700,
    lengthCm: 30,
    widthCm: 24,
    heightCm: 8,
    variants: [
      { id: "var-101-burgundy-s", productId: "prod-101", sku: "101-BUR-S", color: "Burgundy", colorHex: "#7d1837", size: "S", stock: 3, reserved: 1, active: true },
      { id: "var-101-burgundy-m", productId: "prod-101", sku: "101-BUR-M", color: "Burgundy", colorHex: "#7d1837", size: "M", stock: 3, reserved: 1, active: true },
      { id: "var-101-mocha-l", productId: "prod-101", sku: "101-MOC-L", color: "Mocha", colorHex: "#9b735b", size: "L", stock: 3, reserved: 0, active: true },
      { id: "var-101-navy-xl", productId: "prod-101", sku: "101-NAV-XL", color: "Navy", colorHex: "#20344e", size: "XL", stock: 3, reserved: 0, active: true },
    ],
  },
  {
    id: "prod-102",
    code: "102",
    name: "Pearl Crop Cardigan",
    description: "Cardigan cream bertekstur dengan detail kancing mutiara yang bersih.",
    price: 229_000,
    image: "/products/cardigan-102.png",
    images: ["/products/cardigan-102.png"],
    colors: ["Cream", "Latte", "Black"],
    colorHex: { Cream: "#eee2d0", Latte: "#c6a98f", Black: "#242021" },
    sizes: ["S", "M", "L"],
    stock: 8,
    reserved: 1,
    isLive: false,
    active: true,
    weightGrams: 650,
    lengthCm: 28,
    widthCm: 23,
    heightCm: 7,
    variants: [
      { id: "var-102-cream-s", productId: "prod-102", sku: "102-CRE-S", color: "Cream", colorHex: "#eee2d0", size: "S", stock: 3, reserved: 1, active: true },
      { id: "var-102-latte-m", productId: "prod-102", sku: "102-LAT-M", color: "Latte", colorHex: "#c6a98f", size: "M", stock: 3, reserved: 0, active: true },
      { id: "var-102-black-l", productId: "prod-102", sku: "102-BLK-L", color: "Black", colorHex: "#242021", size: "L", stock: 2, reserved: 0, active: true },
    ],
  },
  {
    id: "prod-3303",
    code: "3303",
    name: "Rose Cable Cardigan",
    description: "Cable knit dusty rose dengan siluet sedikit oversized dan hangat.",
    price: 249_000,
    image: "/products/cardigan-3303.png",
    images: ["/products/cardigan-3303.png"],
    colors: ["Dusty Rose", "Oat", "Cocoa"],
    colorHex: { "Dusty Rose": "#b97c87", Oat: "#ded0bb", Cocoa: "#6f5145" },
    sizes: ["M", "L", "XL"],
    stock: 7,
    reserved: 1,
    isLive: false,
    active: true,
    weightGrams: 800,
    lengthCm: 32,
    widthCm: 25,
    heightCm: 9,
    variants: [
      { id: "var-3303-rose-m", productId: "prod-3303", sku: "3303-ROS-M", color: "Dusty Rose", colorHex: "#b97c87", size: "M", stock: 3, reserved: 1, active: true },
      { id: "var-3303-oat-l", productId: "prod-3303", sku: "3303-OAT-L", color: "Oat", colorHex: "#ded0bb", size: "L", stock: 2, reserved: 0, active: true },
      { id: "var-3303-cocoa-xl", productId: "prod-3303", sku: "3303-COC-XL", color: "Cocoa", colorHex: "#6f5145", size: "XL", stock: 2, reserved: 0, active: true },
    ],
  },
];

export const shippingOptions: ShippingOption[] = [
  { id: "ship-jne-reg", courier: "JNE", service: "REG", price: 18_000, eta: "2-3 hari kerja" },
  { id: "ship-jnt-ez", courier: "J&T", service: "EZ", price: 16_000, eta: "2-3 hari kerja" },
  { id: "ship-sicepat-reg", courier: "SiCepat", service: "REG", price: 15_000, eta: "2-4 hari kerja" },
];

export const shippingServices: ShippingService[] = [
  { id: "ship-jne-reg", courierCode: "jne", courierName: "JNE", serviceCode: "reg", serviceName: "REG", flatPrice: 18_000, eta: "2-3 hari kerja", enabled: true, source: "manual" },
  { id: "ship-jnt-ez", courierCode: "jnt", courierName: "J&T", serviceCode: "ez", serviceName: "EZ", flatPrice: 16_000, eta: "2-3 hari kerja", enabled: true, source: "manual" },
  { id: "ship-sicepat-reg", courierCode: "sicepat", courierName: "SiCepat", serviceCode: "reg", serviceName: "REG", flatPrice: 15_000, eta: "2-4 hari kerja", enabled: true, source: "manual" },
];

export const paymentMethods: PaymentMethodConfig[] = defaultPaymentMethods;

const emptyAddress = {
  line: "Jl. Melati No. 15, RT 05/RW 02",
  province: "Jawa Barat",
  city: "Bandung",
  district: "Cicendo",
  postalCode: "40172",
};

export const seedOrders: Order[] = [
  {
    id: "order-seed-1",
    orderNumber: "WEB-1406-001",
    source: "website",
    status: "pending_confirmation",
    productId: "prod-101",
    variantId: "var-101-burgundy-m",
    variantSku: "101-BUR-M",
    productCode: "101",
    productName: "Cardigan Knit Elegance",
    productImage: "/products/cardigan-101.png",
    unitPrice: 199_000,
    quantity: 1,
    color: "Burgundy",
    size: "M",
    buyerName: "Dewi Anjani",
    whatsapp: "0812-3456-3341",
    address: emptyAddress,
    shipping: shippingOptions[0],
    paymentMethod: "bank_transfer",
    proofName: "bukti-transfer-dewi.jpg",
    subtotal: 199_000,
    total: 217_000,
    createdAt: new Date(Date.now() - 4 * 60_000).toISOString(),
    reservedUntil: new Date(Date.now() + 20 * 60_000).toISOString(),
    fulfillmentStatus: "unfulfilled",
  },
  {
    id: "order-seed-2",
    orderNumber: "WA-1406-002",
    source: "whatsapp",
    status: "paid",
    productId: "prod-102",
    variantId: "var-102-cream-s",
    variantSku: "102-CRE-S",
    productCode: "102",
    productName: "Pearl Crop Cardigan",
    productImage: "/products/cardigan-102.png",
    unitPrice: 229_000,
    quantity: 1,
    color: "Cream",
    size: "S",
    buyerName: "Rina Lestari",
    whatsapp: "0857-2210-2210",
    address: { ...emptyAddress, city: "Jakarta Selatan", province: "DKI Jakarta" },
    shipping: shippingOptions[1],
    paymentMethod: "qris",
    proofName: "qris-rina.png",
    subtotal: 229_000,
    total: 245_000,
    createdAt: new Date(Date.now() - 12 * 60_000).toISOString(),
    reservedUntil: new Date(Date.now() - 1 * 60_000).toISOString(),
    paidAt: new Date(Date.now() - 8 * 60_000).toISOString(),
    fulfillmentStatus: "packed",
    packedAt: new Date(Date.now() - 3 * 60_000).toISOString(),
  },
];
