"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Box, CheckCircle2, Clipboard, Copy, ExternalLink, FileImage, Globe2, MessageCircle, PackageCheck, Search, Send, Truck, XCircle } from "lucide-react";
import { PaymentLogo } from "@/components/payment-logo";
import { getPaymentProofUrl, updateOrder, type OrderAction } from "@/lib/api-client";
import { formatRupiah, statusLabel, whatsappInvoiceTemplate } from "@/lib/format";
import type { Order } from "@/lib/types";

type ToastSetter = (toast: { message: string; type: "success" | "error" }) => void;
export function OrderWorkspace({ orders, refresh, toast, whatsappOnly = false }: { orders: Order[]; refresh: () => Promise<void>; toast: ToastSetter; whatsappOnly?: boolean }) {
  const [selectedId, setSelectedId] = useState<string | null>(orders[0]?.id || null);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const [busy, setBusy] = useState(false);
  const [reason, setReason] = useState("Bukti pembayaran belum sesuai.");
  const [waybill, setWaybill] = useState("");
  const [trackingUrl, setTrackingUrl] = useState("");
  const [note, setNote] = useState("");
  const visible = useMemo(() => orders.filter((order) => (!whatsappOnly || order.source === "whatsapp") && (status === "all" || order.status === status) && (!query || [order.orderNumber, order.buyerName, order.productCode, order.whatsapp].join(" ").toLowerCase().includes(query.toLowerCase()))), [orders, whatsappOnly, status, query]);
  const selected = orders.find((order) => order.id === selectedId) || visible[0] || null;
  const packingSlipHref = selected ? `/admin/orders/${selected.id}/print${selected.accessToken ? `?token=${encodeURIComponent(selected.accessToken)}` : ""}` : "#";

  async function action(name: OrderAction, payload: Record<string, unknown> = {}, success: string) {
    if (!selected) return; setBusy(true);
    try { await updateOrder(selected.id, name, payload); await refresh(); toast({ message: success, type: "success" }); }
    catch (error) { toast({ message: error instanceof Error ? error.message : "Aksi pesanan gagal.", type: "error" }); }
    finally { setBusy(false); }
  }
  async function proof() { if (!selected) return; try { const url = await getPaymentProofUrl(selected.id); if (url) window.open(url, "_blank", "noopener,noreferrer"); else toast({ message: "Mode demo tidak menyimpan file bukti asli.", type: "error" }); } catch (error) { toast({ message: error instanceof Error ? error.message : "Bukti gagal dibuka.", type: "error" }); } }
  async function copyInvoice() { if (!selected) return; await navigator.clipboard.writeText(whatsappInvoiceTemplate(selected)); toast({ message: "Ringkasan order disalin untuk WhatsApp.", type: "success" }); }

  return <section className="p-4 sm:p-6"><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#a33c5b]">{whatsappOnly ? "Manual channel" : "Unified inbox"}</p><h1 className="mt-2 font-display text-4xl font-semibold">{whatsappOnly ? "Order WhatsApp" : "Antrean pesanan"}</h1><p className="mt-2 text-sm text-[#756a6e]">Pembayaran dan pengiriman dipisah agar admin tidak salah menganggap order sudah selesai.</p></div><div className="flex gap-2"><label className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#9c8d92]" /><input className="input-shell w-52 pl-9" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari order..." /></label><select className="input-shell w-44" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">Semua status</option><option value="awaiting_payment">Belum bayar</option><option value="pending_confirmation">Perlu dicek</option><option value="paid">Dibayar</option><option value="cancelled">Dibatalkan</option><option value="rejected">Ditolak</option></select></div></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_390px]"><div className="surface overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-xs"><thead className="bg-[#fff8f5] text-[10px] uppercase tracking-[.08em] text-[#817379]"><tr><th className="px-4 py-3">Order</th><th className="px-3 py-3">Buyer</th><th className="px-3 py-3">Produk</th><th className="px-3 py-3">Total</th><th className="px-3 py-3">Pembayaran</th><th className="px-3 py-3">Pengiriman</th></tr></thead><tbody>{visible.map((order) => <tr key={order.id} onClick={() => setSelectedId(order.id)} className={`cursor-pointer border-t border-[#f0e8e7] hover:bg-[#fff9f7] ${selected?.id === order.id ? "bg-[#fff1f4]" : ""}`}><td className="px-4 py-3"><strong>{order.orderNumber}</strong><span className="mt-1 flex items-center gap-1 text-[10px] text-[#817379]">{order.source === "website" ? <Globe2 className="size-3" /> : <MessageCircle className="size-3 text-[#218457]" />}{order.source === "website" ? "Website" : "WhatsApp"}</span></td><td className="px-3 py-3"><strong className="block">{order.buyerName}</strong><span className="text-[10px] text-[#817379]">{order.whatsapp}</span></td><td className="px-3 py-3"><strong>Kode {order.productCode}</strong><span className="block text-[10px] text-[#817379]">{order.color} / {order.size}</span></td><td className="px-3 py-3 font-bold">{formatRupiah(order.total)}</td><td className="px-3 py-3"><div className="flex items-center gap-2"><PaymentLogo payment={order.paymentDetails || { type: order.paymentMethod, name: order.paymentMethod === "qris" ? "QRIS" : "Transfer" }} compact /><Status status={order.status} /></div></td><td className="px-3 py-3"><span className="status-pill status-cancelled">{fulfillmentLabel(order.fulfillmentStatus)}</span></td></tr>)}</tbody></table></div>{!visible.length ? <div className="p-10 text-center text-sm text-[#756a6e]">Belum ada pesanan pada filter ini.</div> : null}</div>
      {selected ? <aside className="surface self-start overflow-hidden xl:sticky xl:top-24"><div className="border-b border-[#eadedd] bg-[#4a1326] p-5 text-white"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold tracking-[.14em] text-[#e9a4b7]">ORDER DETAIL</p><h2 className="mt-1 font-display text-2xl font-semibold">{selected.orderNumber}</h2></div><Status status={selected.status} /></div></div><div className="max-h-[calc(100vh-190px)] overflow-y-auto p-5">
        <div className="flex gap-3"><div className="relative h-24 w-20 shrink-0 overflow-hidden rounded-xl bg-[#f1e7e0]"><Image src={selected.productImage} alt="" fill className="object-cover" sizes="80px" /></div><div><span className="text-xs font-extrabold text-[#a33c5b]">KODE {selected.productCode}</span><h3 className="font-display text-xl font-semibold leading-tight">{selected.productName}</h3><p className="mt-1 text-xs text-[#756a6e]">{selected.color} / {selected.size} · {selected.variantSku}</p><p className="mt-2 text-sm font-bold text-[#8a2949]">{formatRupiah(selected.total)}</p></div></div>
        <div className="mt-5 rounded-2xl border border-[#eadedd] bg-[#fff8f5] p-3"><span className="block text-[10px] font-bold uppercase tracking-[.12em] text-[#817379]">Metode pembayaran</span><div className="mt-2 flex items-center gap-3"><PaymentLogo payment={selected.paymentDetails || { type: selected.paymentMethod, name: selected.paymentMethod === "qris" ? "QRIS" : "Transfer" }} compact /><strong className="text-sm">{selected.paymentDetails?.name || selected.paymentMethod}</strong></div></div>
        <div className="mt-3 grid grid-cols-2 gap-2 text-xs"><Info label="Pembeli" value={selected.buyerName} /><Info label="WhatsApp" value={selected.whatsapp} /><Info label="Kurir" value={`${selected.shipping.courier} ${selected.shipping.service}`} /><Info label="Estimasi" value={selected.shipping.eta} /></div><div className="mt-3 rounded-xl bg-[#fff8f5] p-3 text-xs leading-5"><strong>Alamat</strong><p className="mt-1 text-[#756a6e]">{selected.address.line}, {selected.address.district}, {selected.address.city}, {selected.address.province} {selected.address.postalCode}</p></div>
        {selected.proofName ? <button onClick={proof} className="secondary-button mt-4 w-full"><FileImage className="size-4" /> Buka bukti pembayaran <ExternalLink className="size-3.5" /></button> : null}
        {selected.status === "pending_confirmation" || selected.status === "awaiting_payment" ? <div className="mt-5 space-y-3 rounded-2xl border border-[#e7c5cd] bg-[#fff7f8] p-4"><p className="text-xs font-extrabold text-[#7a1837]">KONFIRMASI MANUAL</p><button disabled={busy} onClick={() => action("confirm", { showInLive: true }, "Pembayaran dikonfirmasi dan notifikasi dikirim ke LIVE.")} className="primary-button w-full"><CheckCircle2 className="size-4" /> Konfirmasi + tampilkan LIVE</button><button disabled={busy} onClick={() => action("confirm", { showInLive: false }, "Pembayaran dikonfirmasi tanpa notifikasi LIVE.")} className="ghost-button w-full"><CheckCircle2 className="size-4" /> Konfirmasi tanpa LIVE</button><textarea className="input-shell text-xs" value={reason} onChange={(e) => setReason(e.target.value)} /><div className="grid grid-cols-2 gap-2"><button disabled={busy} onClick={() => action("reject", { reason }, "Bukti ditolak dan reservasi dilepas.")} className="danger-button"><XCircle className="size-4" /> Tolak</button><button disabled={busy} onClick={() => action("release", {}, "Reservasi dibatalkan.")} className="ghost-button">Batalkan</button></div></div> : null}
        {selected.status === "paid" ? <div className="mt-5 space-y-3 rounded-2xl border border-[#dfe8e3] bg-[#f7fbf9] p-4"><p className="text-xs font-extrabold text-[#197245]">FULFILLMENT</p>{selected.fulfillmentStatus === "unfulfilled" ? <button disabled={busy} onClick={() => action("pack", {}, "Pesanan ditandai sudah dikemas.")} className="primary-button w-full"><Box className="size-4" /> Tandai sudah dikemas</button> : null}{selected.fulfillmentStatus === "packed" ? <><input className="input-shell" value={waybill} onChange={(e) => setWaybill(e.target.value)} placeholder="Nomor resi" /><input className="input-shell" value={trackingUrl} onChange={(e) => setTrackingUrl(e.target.value)} placeholder="URL tracking (opsional)" /><button disabled={busy || !waybill} onClick={() => action("ship", { waybill, trackingUrl }, "Pesanan ditandai sudah dikirim.")} className="primary-button w-full"><Truck className="size-4" /> Kirim pesanan</button></> : null}{selected.fulfillmentStatus === "shipped" ? <button disabled={busy} onClick={() => action("complete", {}, "Pesanan diselesaikan.")} className="primary-button w-full"><PackageCheck className="size-4" /> Tandai selesai</button> : null}{selected.waybill ? <p className="text-xs">Resi: <strong>{selected.waybill}</strong></p> : null}<Link href={packingSlipHref} target="_blank" className="ghost-button w-full"><Clipboard className="size-4" /> Packing slip</Link></div> : null}
        <div className="mt-5"><label className="text-xs font-bold">Catatan admin</label><textarea className="input-shell mt-2 text-xs" value={note || selected.adminNote || ""} onChange={(e) => setNote(e.target.value)} placeholder="Catatan internal..." /><button disabled={busy} onClick={() => action("note", { adminNote: note || selected.adminNote || "" }, "Catatan admin disimpan.")} className="ghost-button mt-2 w-full">Simpan catatan</button></div>
        <button onClick={copyInvoice} className="secondary-button mt-3 w-full"><Copy className="size-4" /> Salin ringkasan WA</button><a href={`https://wa.me/${selected.whatsapp.replace(/\D/g, "").replace(/^0/, "62")}`} target="_blank" rel="noreferrer" className="ghost-button mt-2 w-full"><Send className="size-4" /> Buka WhatsApp buyer</a>
      </div></aside> : null}</div>
  </section>;
}
function Status({ status }: { status: Order["status"] }) { const cls = status === "paid" ? "status-paid" : status === "cancelled" || status === "rejected" ? "status-cancelled" : status === "pending_confirmation" ? "status-waiting" : "status-reserved"; return <span className={`status-pill ${cls}`}>{statusLabel(status)}</span>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[#eadedd] p-3"><span className="block text-[10px] text-[#817379]">{label}</span><strong className="mt-1 block truncate">{value}</strong></div>; }
function fulfillmentLabel(status: Order["fulfillmentStatus"]) { return { unfulfilled: "Belum diproses", packed: "Dikemas", shipped: "Dikirim", completed: "Selesai" }[status]; }
