"use client";

import { useState } from "react";
import { LoaderCircle, Pencil, Plus, Trash2, Truck } from "lucide-react";
import { deleteShippingService, saveShippingService } from "@/lib/api-client";
import { formatRupiah } from "@/lib/format";
import type { ShippingService, ShippingServiceDraft } from "@/lib/types";

const blank: ShippingServiceDraft = { courierCode: "jne", courierName: "JNE", serviceCode: "reg", serviceName: "REG", flatPrice: 18000, eta: "2-3 hari kerja", enabled: true };
type ToastSetter = (toast: { message: string; type: "success" | "error" }) => void;

export function ShippingManager({ services, refresh, toast }: { services: ShippingService[]; refresh: () => Promise<void>; toast: ToastSetter }) {
  const [draft, setDraft] = useState<ShippingServiceDraft>(blank);
  const [busy, setBusy] = useState(false);
  async function save() { setBusy(true); try { await saveShippingService(draft); await refresh(); setDraft(blank); toast({ message: "Layanan kurir berhasil disimpan.", type: "success" }); } catch (error) { toast({ message: error instanceof Error ? error.message : "Kurir gagal disimpan.", type: "error" }); } finally { setBusy(false); } }
  async function remove(id: string) { if (!window.confirm("Hapus layanan kurir ini?")) return; try { await deleteShippingService(id); await refresh(); toast({ message: "Layanan kurir dihapus.", type: "success" }); } catch (error) { toast({ message: error instanceof Error ? error.message : "Kurir gagal dihapus.", type: "error" }); } }
  return <section className="p-4 sm:p-6"><div className="mb-5"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#a33c5b]">Shipping rules</p><h1 className="mt-2 font-display text-4xl font-semibold">Kurir dan ongkir</h1><p className="mt-2 text-sm text-[#756a6e]">Tarif manual menjadi fallback. Jika Biteship aktif, daftar kurir ini menentukan layanan yang boleh ditawarkan.</p></div>
    <div className="grid gap-5 xl:grid-cols-[.75fr_1.25fr]"><div className="surface p-5"><h2 className="font-display text-2xl font-semibold">{draft.id ? "Edit layanan" : "Tambah layanan"}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Kode kurir"><input className="input-shell" value={draft.courierCode} onChange={(e) => setDraft({ ...draft, courierCode: e.target.value })} /></Field><Field label="Nama kurir"><input className="input-shell" value={draft.courierName} onChange={(e) => setDraft({ ...draft, courierName: e.target.value })} /></Field><Field label="Kode layanan"><input className="input-shell" value={draft.serviceCode} onChange={(e) => setDraft({ ...draft, serviceCode: e.target.value })} /></Field><Field label="Nama layanan"><input className="input-shell" value={draft.serviceName} onChange={(e) => setDraft({ ...draft, serviceName: e.target.value })} /></Field><Field label="Ongkir flat"><input className="input-shell" type="number" value={draft.flatPrice} onChange={(e) => setDraft({ ...draft, flatPrice: Number(e.target.value) })} /></Field><Field label="Estimasi"><input className="input-shell" value={draft.eta} onChange={(e) => setDraft({ ...draft, eta: e.target.value })} /></Field></div><label className="mt-4 flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={draft.enabled} onChange={(e) => setDraft({ ...draft, enabled: e.target.checked })} className="size-4 accent-[#8a2949]" /> Tampilkan layanan ini</label><div className="mt-5 flex gap-2"><button onClick={save} disabled={busy} className="primary-button">{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Plus className="size-4" />} Simpan</button>{draft.id ? <button onClick={() => setDraft(blank)} className="ghost-button">Batal</button> : null}</div></div>
      <div className="surface overflow-hidden"><div className="border-b border-[#eadedd] p-5"><h2 className="font-display text-2xl font-semibold">Layanan tersedia</h2></div><div className="divide-y divide-[#eadedd]">{services.map((service) => <div key={service.id} className="flex items-center gap-4 p-4"><span className="grid size-11 place-items-center rounded-2xl bg-[#fff0f3] text-[#8a2949]"><Truck className="size-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><strong>{service.courierName} {service.serviceName}</strong><span className={service.enabled ? "status-pill status-paid" : "status-pill status-cancelled"}>{service.enabled ? "Aktif" : "Nonaktif"}</span></div><p className="mt-1 text-xs text-[#756a6e]">{service.eta} · {service.source === "manual" ? "tarif manual" : "tarif API"}</p></div><strong className="text-sm text-[#8a2949]">{formatRupiah(service.flatPrice)}</strong><button onClick={() => setDraft({ ...service })} className="grid size-9 place-items-center rounded-xl border border-[#eadedd]"><Pencil className="size-4" /></button><button onClick={() => remove(service.id)} className="grid size-9 place-items-center rounded-xl text-[#a52f3a]"><Trash2 className="size-4" /></button></div>)}</div></div></div>
  </section>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-xs font-bold text-[#5f5055]"><span>{label}</span>{children}</label>; }
