"use client";

import { FormEvent, useState } from "react";
import { ClipboardPaste, Copy, LoaderCircle, MessageCircle, Truck, X } from "lucide-react";
import { createOrder, getShippingRates } from "@/lib/api-client";
import { whatsappOrderTemplate } from "@/lib/format";
import type { PaymentMethod, Product, ShippingOption } from "@/lib/types";

type Form = { buyerName: string; whatsapp: string; line: string; province: string; city: string; district: string; postalCode: string; productId: string; variantId: string; paymentMethod: PaymentMethod };
const empty = (products: Product[]): Form => ({ buyerName: "", whatsapp: "", line: "", province: "", city: "", district: "", postalCode: "", productId: products.find((item) => item.isLive)?.id || products[0]?.id || "", variantId: "", paymentMethod: "bank_transfer" });
type ToastSetter = (toast: { message: string; type: "success" | "error" }) => void;

export function WhatsAppOrderModal({ products, close, created, toast }: { products: Product[]; close: () => void; created: () => Promise<void>; toast: ToastSetter }) {
  const [form, setForm] = useState<Form>(() => empty(products));
  const [paste, setPaste] = useState("");
  const [rates, setRates] = useState<ShippingOption[]>([]);
  const [shipping, setShipping] = useState<ShippingOption | null>(null);
  const [busy, setBusy] = useState(false);
  const product = products.find((item) => item.id === form.productId) || products[0];
  const variants = product?.variants.filter((variant) => variant.active && variant.stock - variant.reserved > 0) || [];
  const variant = variants.find((item) => item.id === form.variantId) || variants[0];
  const total = (product?.price || 0) + (shipping?.price || 0);
  const valid = Boolean(product && variant && shipping && form.buyerName && form.whatsapp && form.line && form.city && form.province && /^\d{5}$/.test(form.postalCode));

  function parse() {
    const values: Record<string, string> = {};
    paste.split(/\r?\n/).forEach((line) => { const [label, ...rest] = line.split(":"); if (rest.length) values[label.trim().toLowerCase()] = rest.join(":").trim(); });
    const code = values["kode produk"];
    const parsedProduct = products.find((item) => item.code.toLowerCase() === code?.toLowerCase()) || product;
    const parsedVariant = parsedProduct?.variants.find((item) => item.color.toLowerCase() === values["warna"]?.toLowerCase() && item.size.toLowerCase() === values["ukuran"]?.toLowerCase());
    setForm((current) => ({ ...current, productId: parsedProduct?.id || current.productId, variantId: parsedVariant?.id || "", buyerName: values["nama penerima"] || current.buyerName, whatsapp: values["nomor whatsapp"] || current.whatsapp, line: values["alamat lengkap"] || current.line, district: values["kecamatan"] || current.district, city: values["kota/kabupaten"] || current.city, province: values["provinsi"] || current.province, postalCode: (values["kode pos"] || current.postalCode).replace(/\D/g, "").slice(0, 5) }));
    toast({ message: "Template WhatsApp dibaca. Periksa kembali data dan varian sebelum menyimpan.", type: "success" });
  }
  async function loadRates() { if (!product || !/^\d{5}$/.test(form.postalCode)) return; setBusy(true); try { const result = await getShippingRates(product.id, form.postalCode); setRates(result.rates); setShipping(result.rates[0] || null); } catch (error) { toast({ message: error instanceof Error ? error.message : "Ongkir gagal dimuat.", type: "error" }); } finally { setBusy(false); } }
  async function submit(event: FormEvent) { event.preventDefault(); if (!valid || !product || !variant || !shipping) return; setBusy(true); try { await createOrder({ source: "whatsapp", productId: product.id, variantId: variant.id, productCode: product.code, productName: product.name, productImage: product.image, unitPrice: product.price, quantity: 1, color: variant.color, size: variant.size, buyerName: form.buyerName, whatsapp: form.whatsapp, address: { line: form.line, province: form.province, city: form.city, district: form.district, postalCode: form.postalCode }, shipping, paymentMethod: form.paymentMethod }); await created(); } catch (error) { toast({ message: error instanceof Error ? error.message : "Order WhatsApp gagal dibuat.", type: "error" }); } finally { setBusy(false); } }

  return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-[#210710]/75 p-3 backdrop-blur-sm"><form onSubmit={submit} className="my-4 w-full max-w-5xl overflow-hidden rounded-[28px] bg-[#fffaf7] shadow-2xl"><div className="flex items-center justify-between border-b border-[#eadedd] bg-white px-5 py-4 sm:px-7"><div><p className="text-xs font-bold text-[#218457]">WHATSAPP ORDER</p><h2 className="font-display text-3xl font-semibold">Catat order manual</h2></div><button type="button" onClick={close} className="grid size-10 place-items-center rounded-xl border border-[#eadedd]"><X className="size-4" /></button></div>
    <div className="grid max-h-[82vh] overflow-y-auto lg:grid-cols-[.75fr_1.25fr]"><aside className="border-b border-[#eadedd] bg-[#fff3f6] p-5 lg:border-b-0 lg:border-r"><div className="flex items-center gap-2"><MessageCircle className="size-5 text-[#218457]" /><h3 className="font-display text-2xl font-semibold">Paste chat buyer</h3></div><p className="mt-2 text-xs leading-5 text-[#756a6e]">Buyer mengisi template, admin paste di sini, lalu sistem membaca field yang dikenali.</p><textarea className="input-shell mt-4 min-h-64 font-mono text-xs" value={paste} onChange={(e) => setPaste(e.target.value)} placeholder={whatsappOrderTemplate()} /><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={parse} className="primary-button px-3"><ClipboardPaste className="size-4" /> Baca template</button><button type="button" onClick={() => navigator.clipboard.writeText(whatsappOrderTemplate())} className="ghost-button px-3"><Copy className="size-4" /> Salin template</button></div></aside>
      <div className="p-5 sm:p-7"><div className="grid gap-4 sm:grid-cols-2"><Field label="Produk"><select className="input-shell" value={product?.id || ""} onChange={(e) => { setForm({ ...form, productId: e.target.value, variantId: "" }); setRates([]); setShipping(null); }}>{products.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></Field><Field label="Varian"><select className="input-shell" value={variant?.id || ""} onChange={(e) => setForm({ ...form, variantId: e.target.value })}>{variants.map((item) => <option key={item.id} value={item.id}>{item.color} / {item.size} · stok {item.stock - item.reserved}</option>)}</select></Field><Field label="Nama penerima"><input required className="input-shell" value={form.buyerName} onChange={(e) => setForm({ ...form, buyerName: e.target.value })} /></Field><Field label="WhatsApp"><input required className="input-shell" value={form.whatsapp} onChange={(e) => setForm({ ...form, whatsapp: e.target.value })} /></Field><div className="sm:col-span-2"><Field label="Alamat lengkap"><textarea required className="input-shell" value={form.line} onChange={(e) => setForm({ ...form, line: e.target.value })} /></Field></div><Field label="Kecamatan"><input className="input-shell" value={form.district} onChange={(e) => setForm({ ...form, district: e.target.value })} /></Field><Field label="Kota/Kabupaten"><input className="input-shell" value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} /></Field><Field label="Provinsi"><input className="input-shell" value={form.province} onChange={(e) => setForm({ ...form, province: e.target.value })} /></Field><Field label="Kode pos"><div className="flex gap-2"><input className="input-shell" value={form.postalCode} onChange={(e) => { setForm({ ...form, postalCode: e.target.value.replace(/\D/g, "").slice(0, 5) }); setShipping(null); }} /><button type="button" onClick={loadRates} disabled={busy || !/^\d{5}$/.test(form.postalCode)} className="ghost-button shrink-0 px-3"><Truck className="size-4" /></button></div></Field></div>
        {rates.length ? <div className="mt-4 grid gap-2 sm:grid-cols-2">{rates.map((rate) => <label key={rate.id} className={`cursor-pointer rounded-xl border p-3 text-xs ${shipping?.id === rate.id ? "border-[#df5276] bg-[#fff0f4]" : "border-[#eadedd] bg-white"}`}><input type="radio" className="mr-2 accent-[#8a2949]" checked={shipping?.id === rate.id} onChange={() => setShipping(rate)} /><strong>{rate.courier} {rate.service}</strong><span className="mt-1 block text-[#756a6e]">Rp{rate.price.toLocaleString("id-ID")} · {rate.eta}</span></label>)}</div> : null}
        <div className="mt-5 flex items-center justify-between rounded-2xl bg-[#4a1326] p-4 text-white"><div><span className="text-xs text-white/65">Total order</span><strong className="mt-1 block text-2xl">Rp{total.toLocaleString("id-ID")}</strong></div><button disabled={!valid || busy} className="primary-button border-white/20 bg-white text-[#4a1326] shadow-none">{busy ? <LoaderCircle className="size-4 animate-spin" /> : null} Simpan & reservasi</button></div>
      </div></div></form></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-xs font-bold text-[#5f5055]"><span>{label}</span>{children}</label>; }
